// Mocks generated by Mockito 5.4.2 from annotations
// in example/test/home/data/repository/home_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:eitherx/eitherx.dart' as _i2;
import 'package:example/core/base/base_response.dart' as _i6;
import 'package:example/home/data/data-sources/home_remote_data_source.dart'
    as _i3;
import 'package:example/home/data/models/device_settings_model.dart' as _i9;
import 'package:example/home/data/models/governorate_model.dart' as _i7;
import 'package:example/home/data/models/result_model.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mwidgets/mwidgets.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i3.HomeRemoteDataSource {
  @override
  _i4.Future<
      _i2.Either<_i5.Failure,
          _i6.BaseResponse<List<_i7.GovernorateModel>?>>> getGovernorates() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGovernorates,
          [],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure,
                    _i6.BaseResponse<List<_i7.GovernorateModel>?>>>.value(
            _FakeEither_0<_i5.Failure,
                _i6.BaseResponse<List<_i7.GovernorateModel>?>>(
          this,
          Invocation.method(
            #getGovernorates,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2.Either<_i5.Failure,
                    _i6.BaseResponse<List<_i7.GovernorateModel>?>>>.value(
            _FakeEither_0<_i5.Failure,
                _i6.BaseResponse<List<_i7.GovernorateModel>?>>(
          this,
          Invocation.method(
            #getGovernorates,
            [],
          ),
        )),
      ) as _i4.Future<
          _i2
          .Either<_i5.Failure, _i6.BaseResponse<List<_i7.GovernorateModel>?>>>);
  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i6.BaseResponse<_i8.ResultModel?>>> getResult({
    required int? countryId,
    int? termId,
    String? studentName,
    String? sittingNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResult,
          [],
          {
            #countryId: countryId,
            #termId: termId,
            #studentName: studentName,
            #sittingNumber: sittingNumber,
          },
        ),
        returnValue: _i4.Future<
                _i2
                .Either<_i5.Failure, _i6.BaseResponse<_i8.ResultModel?>>>.value(
            _FakeEither_0<_i5.Failure, _i6.BaseResponse<_i8.ResultModel?>>(
          this,
          Invocation.method(
            #getResult,
            [],
            {
              #countryId: countryId,
              #termId: termId,
              #studentName: studentName,
              #sittingNumber: sittingNumber,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2
                .Either<_i5.Failure, _i6.BaseResponse<_i8.ResultModel?>>>.value(
            _FakeEither_0<_i5.Failure, _i6.BaseResponse<_i8.ResultModel?>>(
          this,
          Invocation.method(
            #getResult,
            [],
            {
              #countryId: countryId,
              #termId: termId,
              #studentName: studentName,
              #sittingNumber: sittingNumber,
            },
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.BaseResponse<_i8.ResultModel?>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.BaseResponse<int>>> addFavorite(
          {required int? countryId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [],
          {#countryId: countryId},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.BaseResponse<int>>>.value(
                _FakeEither_0<_i5.Failure, _i6.BaseResponse<int>>(
          this,
          Invocation.method(
            #addFavorite,
            [],
            {#countryId: countryId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.BaseResponse<int>>>.value(
                _FakeEither_0<_i5.Failure, _i6.BaseResponse<int>>(
          this,
          Invocation.method(
            #addFavorite,
            [],
            {#countryId: countryId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.BaseResponse<int>>>);
  @override
  _i4.Future<
          _i2.Either<_i5.Failure, _i6.BaseResponse<_i9.DeviceSettingsModel?>>>
      updateUser({required int? firebaseToken}) => (super.noSuchMethod(
            Invocation.method(
              #updateUser,
              [],
              {#firebaseToken: firebaseToken},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i9.DeviceSettingsModel?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i9.DeviceSettingsModel?>>(
              this,
              Invocation.method(
                #updateUser,
                [],
                {#firebaseToken: firebaseToken},
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i9.DeviceSettingsModel?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i9.DeviceSettingsModel?>>(
              this,
              Invocation.method(
                #updateUser,
                [],
                {#firebaseToken: firebaseToken},
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  _i6.BaseResponse<_i9.DeviceSettingsModel?>>>);
}
