targets:
  $default:
    builders:
      generate:
        enabled: true

builders:
  generate:
    import: "package:clean_architecture_generator/clean_architecture_generator.dart"
    builder_factories: [ "generateArchitecture", ]
    build_extensions:
      ".dart":
        - ".g.dart"
    auto_apply: dependents
    build_to: source
    applies_builders: [ "source_gen|combining_builder" ]