targets:
  $default:
    builders:
      generate:
        enabled: true

builders:
  generate:
    import: "package:mvvm_generator/mvvm_generator.dart"
    builder_factories: [ "generateMVVM", ]
    build_extensions:
      ".dart":
        - ".g.dart"
    auto_apply: dependents
    build_to: source
    applies_builders: [ "source_gen|combining_builder" ]