targets:
  $default:
    builders:
      generate:
        enabled: true

builders:
  generate:
    import: "package:generators/generators.dart"
    builder_factories: [ "generateUseCase","generateCubit","generateUseCaseUnitTest","generateCubitUnitTest" ,"generateRequests","generateRepository" ]
    build_extensions:
      ".dart":
        - ".g.dart"
    auto_apply: dependents
    build_to: source
    applies_builders: [ "source_gen|combining_builder" ]