name: clean_architecture_generator
description: A flutter package that generates clean architecture code with testing case for that from retrofit code.
version: 0.0.1
homepage: https://github.com/ibrahimnashat/clean_architecture_generator.git

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  build: ^2.4.1
  source_gen: ^1.4.0
  analyzer: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6

flutter:


