name: clean_architecture_generator
description: A flutter package that generates clean architecture code with testing case for that from retrofit code.
homepage: https://github.com/ibrahimnashat/clean_architecture_generator.git

version: 0.1.5

environment:
  sdk: '>=2.17.0  <4.0.0'

dependencies:
  build: ^2.4.1
  source_gen: ^1.4.0
  analyzer: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.6



