name: clean_architecture_generator
description: A flutter package that generates clean architecture code with testing case for that from retrofit code.
homepage: https://github.com/ibrahimnashat/clean_architecture_generator.git

version: 0.1.3

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.1
  source_gen: ^1.4.0
  analyzer: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6



