// Mocks generated by Mockito 5.4.2 from annotations
// in example/test/home/domain/use-cases/add_comment6_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:eitherx/eitherx.dart' as _i2;
import 'package:example/core/base/base_response.dart' as _i6;
import 'package:example/home/data/models/device_settings_model.dart' as _i8;
import 'package:example/home/domain/entities/device_settings_entity.dart'
    as _i7;
import 'package:example/home/domain/repository/home_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mwidgets/mwidgets.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i3.HomeRepository {
  @override
  _i4.Future<
          _i2.Either<_i5.Failure, _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>
      addComment({
    required String? storyId1,
    required String? content1,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #addComment,
              [],
              {
                #storyId1: storyId1,
                #content1: content1,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment,
                [],
                {
                  #storyId1: storyId1,
                  #content1: content1,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment,
                [],
                {
                  #storyId1: storyId1,
                  #content1: content1,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>);
  @override
  _i4.Future<
          _i2.Either<_i5.Failure, _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>
      addComment2({
    required String? storyId2,
    required String? content2,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #addComment2,
              [],
              {
                #storyId2: storyId2,
                #content2: content2,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment2,
                [],
                {
                  #storyId2: storyId2,
                  #content2: content2,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment2,
                [],
                {
                  #storyId2: storyId2,
                  #content2: content2,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>);
  @override
  _i4.Future<
          _i2.Either<_i5.Failure, _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>
      addComment3({
    required String? storyId,
    required String? content,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #addComment3,
              [],
              {
                #storyId: storyId,
                #content: content,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment3,
                [],
                {
                  #storyId: storyId,
                  #content: content,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment3,
                [],
                {
                  #storyId: storyId,
                  #content: content,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>);
  @override
  _i4.Future<
          _i2.Either<_i5.Failure, _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>
      addComment4({
    required String? storyId,
    required String? content,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #addComment4,
              [],
              {
                #storyId: storyId,
                #content: content,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment4,
                [],
                {
                  #storyId: storyId,
                  #content: content,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment4,
                [],
                {
                  #storyId: storyId,
                  #content: content,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>);
  @override
  _i4.Future<
          _i2.Either<_i5.Failure, _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>
      addComment5({
    required String? storyId,
    required String? content,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #addComment5,
              [],
              {
                #storyId: storyId,
                #content: content,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment5,
                [],
                {
                  #storyId: storyId,
                  #content: content,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment5,
                [],
                {
                  #storyId: storyId,
                  #content: content,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> cacheAddComment5(
          {required _i8.DeviceSettingsModel? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAddComment5,
          [],
          {#data: data},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #cacheAddComment5,
            [],
            {#data: data},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #cacheAddComment5,
            [],
            {#data: data},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
  @override
  _i2.Either<_i5.Failure, _i7.DeviceSettingsEntity> getCacheAddComment5() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCacheAddComment5,
          [],
        ),
        returnValue: _FakeEither_0<_i5.Failure, _i7.DeviceSettingsEntity>(
          this,
          Invocation.method(
            #getCacheAddComment5,
            [],
          ),
        ),
        returnValueForMissingStub:
            _FakeEither_0<_i5.Failure, _i7.DeviceSettingsEntity>(
          this,
          Invocation.method(
            #getCacheAddComment5,
            [],
          ),
        ),
      ) as _i2.Either<_i5.Failure, _i7.DeviceSettingsEntity>);
  @override
  _i4.Future<
          _i2.Either<_i5.Failure, _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>
      addComment6({
    required String? storyId1,
    required String? content1,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #addComment6,
              [],
              {
                #storyId1: storyId1,
                #content1: content1,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment6,
                [],
                {
                  #storyId1: storyId1,
                  #content1: content1,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment6,
                [],
                {
                  #storyId1: storyId1,
                  #content1: content1,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>);
  @override
  _i4.Future<
          _i2.Either<_i5.Failure, _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>
      addComment7({
    required String? storyId2,
    required String? content2,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #addComment7,
              [],
              {
                #storyId2: storyId2,
                #content2: content2,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment7,
                [],
                {
                  #storyId2: storyId2,
                  #content2: content2,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment7,
                [],
                {
                  #storyId2: storyId2,
                  #content2: content2,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>);
  @override
  _i4.Future<
          _i2.Either<_i5.Failure, _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>
      addComment8({
    required String? storyId3,
    required String? content3,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #addComment8,
              [],
              {
                #storyId3: storyId3,
                #content3: content3,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment8,
                [],
                {
                  #storyId3: storyId3,
                  #content3: content3,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i6.BaseResponse<_i7.DeviceSettingsEntity?>>(
              this,
              Invocation.method(
                #addComment8,
                [],
                {
                  #storyId3: storyId3,
                  #content3: content3,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  _i6.BaseResponse<_i7.DeviceSettingsEntity?>>>);
}
