// Mocks generated by Mockito 5.4.2 from annotations
// in example/test/home/data/data-sources/home_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:example/core/base/base_response.dart' as _i2;
import 'package:example/core/base/network.dart' as _i6;
import 'package:example/home/data/client-services/home_client_services.dart'
    as _i3;
import 'package:example/home/data/models/device_settings_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseResponse_0<T> extends _i1.SmartFake
    implements _i2.BaseResponse<T> {
  _FakeBaseResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeClientServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeClientServices extends _i1.Mock
    implements _i3.HomeClientServices {
  @override
  _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>> addComment({
    required String? storyId1,
    required String? content1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [],
          {
            #storyId1: storyId1,
            #content1: content1,
          },
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment,
            [],
            {
              #storyId1: storyId1,
              #content1: content1,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment,
            [],
            {
              #storyId1: storyId1,
              #content1: content1,
            },
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>);
  @override
  _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>> addComment2({
    required String? storyId2,
    required String? content2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment2,
          [],
          {
            #storyId2: storyId2,
            #content2: content2,
          },
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment2,
            [],
            {
              #storyId2: storyId2,
              #content2: content2,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment2,
            [],
            {
              #storyId2: storyId2,
              #content2: content2,
            },
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>);
  @override
  _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>> addComment3({
    required String? storyId,
    required String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment3,
          [],
          {
            #storyId: storyId,
            #content: content,
          },
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment3,
            [],
            {
              #storyId: storyId,
              #content: content,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment3,
            [],
            {
              #storyId: storyId,
              #content: content,
            },
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>);
  @override
  _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>> addComment4({
    required String? storyId,
    required String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment4,
          [],
          {
            #storyId: storyId,
            #content: content,
          },
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment4,
            [],
            {
              #storyId: storyId,
              #content: content,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment4,
            [],
            {
              #storyId: storyId,
              #content: content,
            },
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>);
  @override
  _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>> addComment5({
    required String? storyId,
    required String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment5,
          [],
          {
            #storyId: storyId,
            #content: content,
          },
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment5,
            [],
            {
              #storyId: storyId,
              #content: content,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment5,
            [],
            {
              #storyId: storyId,
              #content: content,
            },
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>);
  @override
  _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>> addComment6({
    required String? storyId1,
    required String? content1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment6,
          [],
          {
            #storyId1: storyId1,
            #content1: content1,
          },
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment6,
            [],
            {
              #storyId1: storyId1,
              #content1: content1,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment6,
            [],
            {
              #storyId1: storyId1,
              #content1: content1,
            },
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>);
  @override
  _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>> addComment7({
    required String? storyId2,
    required String? content2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment7,
          [],
          {
            #storyId2: storyId2,
            #content2: content2,
          },
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment7,
            [],
            {
              #storyId2: storyId2,
              #content2: content2,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment7,
            [],
            {
              #storyId2: storyId2,
              #content2: content2,
            },
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>);
  @override
  _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>> addComment8({
    required String? storyId3,
    required String? content3,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment8,
          [],
          {
            #storyId3: storyId3,
            #content3: content3,
          },
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment8,
            [],
            {
              #storyId3: storyId3,
              #content3: content3,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>.value(
                _FakeBaseResponse_0<_i5.DeviceSettingsModel?>(
          this,
          Invocation.method(
            #addComment8,
            [],
            {
              #storyId3: storyId3,
              #content3: content3,
            },
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i5.DeviceSettingsModel?>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
